ALTER TABLE library_book ADD COLUMN purchase_price NUMERIC(38,2) DEFAULT 0 NOT NULL;
ALTER TABLE library_book ADD COLUMN selling_price NUMERIC(38,2) DEFAULT 0 NOT NULL;
ALTER TABLE sale_item ADD COLUMN unit_price NUMERIC(38,2) DEFAULT 0 NOT NULL;
